project:
  type: website

website:
  title: "Exploring Birds of North America"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [yeti, custom.scss]
    toc: true



