project:
  type: website

website:
  title: "Exploring Birds of Genesee County, Michigan"
  favicon: images/logo.png
  page-navigation: true
  sidebar:
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Recent Sightings
      - href: notable_obs.qmd
        text: Notable Observations
        

format:
  html:
    theme: [yeti, custom.scss]
    toc: true
    grid: 
      sidebar-width: 175px
      



