project:
  type: website

website:
  title: "Exploring Birds of Michigan"
  favicon: images/logo.png
  page-navigation: true
  navbar: 
    search: true
    collapse: true
    logo: "images/logo.png"
    left: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Recent Sightings
      - href: notable_obs.qmd
        text: Notable Observations
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Recent Sightings
      - href: notable_obs.qmd
        text: Notable Observations
        

format:
  html:
    theme: [yeti, custom.scss]
    toc: true
    grid: 
      sidebar-width: 250px
      



