---
title: "Recent Michigan Bird Sightings"
format: 
  dashboard:
    orientation: columns
---

## Column1 {width = "35%"}

```{r, loadpackages}
#| echo: false
#| include: false
library(tidyverse)
library(httr2)
library(gt)
library(tidygeocoder)
```


```{r, getrecentobservations}

#Define ebird API key.
api_key <- Sys.getenv("api_key")

#API Call
recent_obs <- request("https://api.ebird.org/v2/data/obs/US-MI/recent") |> 
  req_headers(
    `X-eBirdApiToken` = api_key,
  ) |> 
  req_perform() |>
  resp_body_json()

# Convert to tibble
recent_obs_df <- map_dfr(recent_obs, ~ as_tibble(.x))
```

```{r, obtaincityinfo}
# Reverse geocode to obtain the city from the latitude/longitude coordinates.
loc_city <- recent_obs_df |> 
  reverse_geocode(lat = lat, long = lng, method = 'arcgis', 
                  address = address, full_results = TRUE) |>
  select(locId, City) |>
  group_by(locId) |>
  slice(1) |>
  ungroup()
```
```{r, obtaincountyinfo}
# Reverse geocode to obtain the county from the latitude/longitude coordinates.

loc_county <- recent_obs_df |> 
  reverse_geocode(lat = lat, long = lng, method = 'arcgis', 
                  address = address, full_results = TRUE) |>
  select(locId, Subregion) |>
  group_by(locId) |>
  slice(1) |>
  ungroup()
```


```{r, combine tibbles}
# Combine the recent observations with the city and county data.

recent_obs_df <- left_join(recent_obs_df, loc_city, by = "locId")
recent_obs_df <- left_join(recent_obs_df, loc_county, by = "locId")
```


```{r, createtable1}
# Sort recent_obs_df alphabetically by county.
recent_obs_df <- recent_obs_df |>
  arrange(Subregion)

# Create dashboard table
recent_obs_df |>
  select(comName, obsDt, City, locName, howMany, Subregion) |>
  gt(groupname_col = "Subregion") |>
  tab_header(
    title = md("**Recent Michigan Bird Sightings**")) |>
  cols_label(
    comName = md("**Common Name**"),
    obsDt = md("**Date**"),
    City = md("**City**"),
    locName = md("**Location**"),
    howMany = md("**Number Observed**")
  ) |>
  fmt_number(columns = howMany, decimals = 0) |>
  fmt_date(columns = obsDt, date_style = "yMd") |>
  tab_source_note(
    source_note = md("**Source: [ebird.org](https://ebird.org) Web API**")
  ) |>
  tab_options(
    table.font.size = px(14),
     row_group.font.weight = "bold" 
  ) 

```


## Column2 {width = "65%"}
### Row {.row1}

```{r, sendtoojs}
#| echo: false
#| include: false

# The R tibble must be passed to Observable JavaScript before it can be accessed in
# an OJS cell.
ojs_define(recent_obs_ojs = recent_obs_df)
```

```{ojs, createCountyDropdown}
//| expandable: false

// Transpose the data to make it usable in ojs.
recent_observations = transpose(recent_obs_ojs)

// Create a dropdown menu of the county name.
viewof countyNameDropdown = Inputs.select(
  Array.from(new Set(recent_observations.map(d => d.Subregion))),
  {
    label: "Choose a county",
    unique: true, // Only include each location once.
    sort: true // Sort the options alphabetically.
    }
)
```

### Row{.row1a}
```{ojs, createCityDropdown}
//| expandable: false

// Create a dropdown menu of the city name.
viewof cityNameDropdown = Inputs.select(
  Array.from(new Set(recent_observations.filter(d => d.Subregion === countyNameDropdown)
  .map(d => d.City))),
  {
    label: "Choose a city",
    unique: true, // Only include each location once.
    sort: true // Sort the options alphabetically.
    }
)
```


### Row{.row1b}

```{ojs, createLocDropdown}
//| expandable: false
//| label: loc-dropdown

// Create a dropdown menu of the location name.
viewof selected_location = Inputs.select(
  Array.from(new Set(recent_observations.filter(d => d.City === cityNameDropdown)
  .map(d => d.locName))),
  {
    label: "Choose a location",
    unique: true, // Only include each location once.
    sort: true // Sort the options alphabetically.
    }
)
```

### Row {.row2}

```{ojs, createBarChart}
//| expandable: false

// Filter to only the location selected from the dropdown.
filtered_observations = recent_observations.filter(d => d.locName === selected_location)

// Create a horizontal bar graph using Observable Plot.
Plot.plot({
  title: "Recent Observations for " + selected_location,
  marginLeft: 150,
  height: filtered_observations.length * 25 + 100,
  width: undefined,
  x: {
    label: "Number Observed"
  },
  y: {
    label: "Species Common Name"
  },
  marks: [
    Plot.barX(filtered_observations, {
      x: "howMany",
      y: "comName",
      sort: { y: "x", reverse: true }, // Sort data largest to smallest.
      fill: "#888"
    }),
    // Add data labels.
   Plot.text(filtered_observations, {
      x: "howMany",
      y: "comName",
      text: d => d.howMany, 
      dx: -15,
      dy: 0,
      fill: "#fff",
      textAnchor: "start",
    }),
  ]
})
```

### Row {.row3}
:::{.card expandable="false"}
<div style="background-color: #333; color: white; border-radius: 10px; padding: 10px; display: flex; align-items: center">

  <span style="font-size: 1vw; width: 100%;">
    This dashboard was created by Haley McDowell for Oakland University MIS 5470 Winter 2025 Practical Computing for Data Analytics course Final Project.<br> The code for this dashboard can be found [here](https://github.com/haleymcdowell/pfw-dashboard).
  </span>

</div>
:::

