---
title: "Hotspots"
format: 
  dashboard:
    orientation: columns
---

## Column1 {width = "35%"}

```{r, loadpackages}
#| echo: false
#| include: false
library(tidyverse)
library(httr2)
library(gt)
library("rebird")
```

```{r, gethotspots}

#Define ebird API key.
api_key <- Sys.getenv("api_key")

#Define region.
region_code <- "US-MI"

#Get hotspots.
hotspots <- ebirdhotspotlist("US-MI", key = api_key)
```
```{r, getsubregionnames}

#API Call
subregions <- request("https://api.ebird.org/v2/ref/region/list/subnational2/US-MI") |> 
  req_headers(
    `X-eBirdApiToken` = api_key,
  ) |> 
  req_perform() |>
  resp_body_json()

# Convert to tibble
subregions_df <- map_dfr(subregions, ~ as_tibble(.x))
```

```{r, combinetibbles}

# Combine hotspots and subregions_df on the subnational2Code.
hotspots_df <- left_join(hotspots, subregions_df, by = c("subnational2Code" = "code"))
```

```{r, createtable}
# Create dashboard table
hotspots_df |>
  select(locName, name, numSpeciesAllTime) |>
  arrange(desc(numSpeciesAllTime)) |>
  gt() |>
  tab_header(
    title = md("**Hotspots in Michigan**")) |>
  cols_label(
    locName = md("**Location**"),
    name = md("**County**"),
    numSpeciesAllTime = md("**Number of Species Observed**")
  ) |>
  fmt_number(columns = numSpeciesAllTime, decimals = 0) |>
  tab_source_note(
    source_note = md("**Source: [ebird.org](https://ebird.org) Web API**")
  ) |>
  tab_options(
    table.font.size = px(14)
  )
```

## Column2 {width = "65%"}

### Row {.row1}

```{r, sendtoojs}
#| echo: false
#| include: false

# The R tibble must be passed to Observable JavaScript before it can be accessed in
# an OJS cell.
ojs_define(hotspots_ojs = hotspots_df)
```

```{ojs, createCountyDropdown}
//| expandable: false

// Transpose the data to make it usable in ojs.
mi_hotspots = transpose(hotspots_ojs)

// Create a dropdown menu of the location name.
viewof countyNameDropdown = Inputs.select(
  mi_hotspots.map(d => d.name),
  {
    label: "Choose a county",
    unique: true, // Only include each location once.
    sort: true // Sort the options alphabetically.
    }
)

```

### Row {.row2}

```{ojs, createBarChart}
//| expandable: false

// Filter to only the county selected from the dropdown.
filtered_hotspots = mi_hotspots.filter(d => d.name === countyNameDropdown)

// Create a horizontal bar graph using Observable Plot.
Plot.plot({
  title: "Hotspots for " + countyNameDropdown + " county",
  marginLeft: 250,
  height: filtered_hotspots.length * 25 + 100,
  width: undefined,
  x: {
    label: "Number of Species Observed"
  },
  y: {
    label: "Location Name"
  },
  marks: [
    Plot.barX(filtered_hotspots, 
    Plot.groupY(
      {x: "sum"}, // Take the sum of the numSpeciesAllTime values for each location.
      {y: "locName", 
      x: "numSpeciesAllTime",
      sort: { y: "x", reverse: true }, // Sort data largest to smallest.
      fill: "#888"})),
    // Add data labels
    Plot.text(filtered_hotspots, 
      Plot.groupY(
      {x: "sum"}, 
      {y: "locName", 
      x: "numSpeciesAllTime",
      text: d => d3.sum(d.map(x => x.numSpeciesAllTime)),
      dx: -25,
      dy: 0,
      fill: "#fff",
      textAnchor: "start",
    })),
      ]
})
     
```

### Row {.row3}
:::{.card expandable="false"}
<div style="background-color: #333; color: white; border-radius: 10px; padding: 10px; display: flex; align-items: center">

  <span style="font-size: 1vw; width: 100%;">
    This dashboard was created by Haley McDowell for Oakland University MIS 5470 Winter 2025 Practical Computing for Data Analytics course Final Project.<br> The code for this dashboard can be found [here](https://github.com/haleymcdowell/pfw-dashboard).
  </span>

</div>
:::