---
title: "Exploring Birds of Michigan"
---

My name is Haley McDowell. I am a graduate student at Oakland University pursuing my Master's Degree in Business Analytics.

This dashboard site was created for my MIS 5470 Practical Computing for Data Analytics final course project. It utilizes the [ebird.org](https://ebird.org) public web API to pull recent bird sightings located near Genesee County, Michigan as well as notable Michigan bird sightings into interactive dashboards.

The bones of this dashboard were created with help from the fantastic tutorial series on creating Quarto dashboards in R and publishing them via GitHub Pages and GitHub Actions by Melissa Van Bussel. Her series can be found [here](https://melissavanbussel.github.io/spotify-dashboard/tutorial.html). Her dashboard site can be viewed [here](https://melissavanbussel.github.io/spotify-dashboard/).

Packages used in the creation of this dashboard include Observable Plot, gt, httr2, and tidyverse.

The code for this dashboard can be found [here](https://github.com/haleymcdowell/pfw-dashboard).

The [Recent Sightings](https://haleymcdowell.github.io/pfw-dashboard/dashboard.html) page lists all recent bird sightings in Genesee County, Michigan. There is an option to filter to specific locations within the county.

The [Notable Observations](https://haleymcdowell.github.io/pfw-dashboard/notable_obs.html) displays all notable bird sightings in Michigan from the last 30 days. Per eBird, "Notable observations can be for locally or nationally rare species or are otherwise unusual, e.g. over-wintering birds in a species which is normally only a summer visitor." There is the option to filter to specific counties within the state.

<iframe src="https://macaulaylibrary.org/asset/634051406/embed" height="507" width="640" frameborder="0" allowfullscreen></iframe>